const TRANSLATIONS = {
  "JOIN": "참여하기",
  "welcome to TETR.IO": "TETR.IO에 오신 걸 환영해요",
  "puzzle together in this modern yet familiar online stacker. play against friends and foes all over the world, or claim a spot on the leaderboards - the stacker future is yours!": "현대적이면서도 친숙한 온라인 스태커에서 함께 퍼즐을 맞춰 보세요. 전 세계의 친구 및 적과 대결하거나 순위표에서 한 자리를 차지하세요 - 스태커의 미래는 당신 거예요!",
  "enter a username to join, or leave it blank to get a random one": "참여할 닉네임을 입력해 주세요. 랜덤으로 닉네임을 얻으려면 비워 두세요",
  "TETR.IO is in ALPHA. please report bugs when you see them!": "TETR.IO는 현재 알파 버전이에요. 버그를 발견하면 신고해 주세요!",
  "by joining, you accept the ": "참여함으로써, 다음에 동의하는 것으로 간주돼요: ",
  "terms of use": "이용 약관",
  "privacy policy": "개인 정보 처리 방침",
  " and ": " 그리고 ",
  "rules": "규칙",
  "PLAY": "플레이",
  "TETRA CHANNEL": "테트라 채널",
  "ABOUT": "정보",
  "total players": "총 플레이어 수",
  "games played": "판 플레이됨",
  "hours played": "시간 플레이됨",
  "good to see you again!": "다시 만나서 반가워요!",
  "BACK": "뒤로",
  "I FORGOT": "잊어버렸어요",
  "LOGIN": "로그인",
  "password incorrect": "비밀번호가 틀렸어요",
  "PASSWORD": "비밀번호",
  "want to join?": "가입하고 싶으신가요?",
  "the nickname ": "닉네임 ",
  " hasn't been registered. do you want to claim it as yours, or play anonymously? you won't be able to submit scores to the leaderboards or play in matchmaking when anonymous.": "은(는) 등록돼 있지 않아요. 이 닉네임을 가지고 등록하시겠어요, 아니면 익명으로 플레이하시겠어요? 익명으로 플레이할 경우 순위표에 점수를 제출하거나 매치 메이킹에서 플레이할 수 없어요.",
  "stay ANONYMOUS": "익명 유지하기",
  "let's make things official": "공식화해 봅시다",
  "to register, please choose a password for yourself": "등록하려면 비밀번호를 직접 선택해 주세요.",
  "password must be at least 6 characters": "비밀번호는 최소 6자 이상이어야 해요",
  "those passwords don't match": "비밀번호가 일치하지 않아요",
  "just to be sure…": "확실히 하기 위해…",
  "please enter the characters above": "위 문자들을 입력해 주세요",
  "if the email you entered was correct, you should be receiving an email shortly!": "입력한 이메일이 맞는다면, 곧 이메일을 받으실 수 있을 거예요!",
  "ANONYMOUS USERS CANNOT SET RECORDS": "익명 유저는 기록을 세울 수 없어요", // 미적용, data-block-reason
  "ANONYMOUS USERS MAY NOT ENTER TETRA LEAGUE": "익명 유저는 테트라 리그에 진입할 수 없어요", // 미적용, data-block-reason
  "Ǳ VIEW FULL": "Ǳ 전체 보기",
  "Ǳ MY PAGE": "Ǳ 내 페이지",
  "GET READY FOR": "다음 배틀을",
  "THE NEXT BATTLE": "준비하세요",
  "RECENT": "최근",
  "view your achievements!": "자신의 성과를 확인하세요!",
  "view other players and their achievements!": "다른 플레이어와 그들의 성과를 확인하세요!",
  "fetching records…": "기록 불러오는 중…",
  "fetching replay…": "리플레이 불러오는 중…",
  "FINAL TIME": "최종 시간",
  "replay id:": "리플레이 id", // 미적용, .replayid::before
  "opening replay": "리플레이 여는 중 ",
  "FINAL SCORE": "최종 점수",
  "STATS": "통계",
  "BLITZ played by ": "블리츠 플레이 by ",
  "40 LINES played by ": "40줄 플레이 by ",
  "OVERVIEW": "개요",
  "FULL": "전체",
  "LEVEL": "레벨",
  "PIECES PLACED": "놓은 블록",
  "PIECES per SECOND": "초당 블록",
  "KEYS PRESSED": "누른 키",
  "KEYS per PIECE": "블록당 키",
  "KEYS per SECOND": "초당 키",
  "HOLDS": "홀드",
  "SCORE": "점수",
  "TIME": "시간",
  "LINES": "줄",
  "LINES per MINUTE": "분당 줄",
  //"T-spins": "T-스핀",
  "maximum COMBO": "최대 콤보",
  "maximum back-to-back chain": "최대 백-투-백 체인",
  "ALL CLEARS": "올 클리어",
  "finesse %": "피네스 %",
  "finesse faults": "피네스 실수",
  "SINGLES": "싱글",
  "DOUBLES": "더블",
  "TRIPLES": "트리플",
  "QUADS": "쿼드",
  "T-spin MINIS": "T-스핀 미니",
  "T-spin MINI SINGLES": "T-스핀 미니 싱글",
  "T-spin SINGLES": "T-스핀 싱글",
  "T-spin MINI DOUBLES": "T-스핀 미니 더블",
  "T-spin DOUBLES": "T-스핀 더블",
  "T-spin TRIPLES": "T-스핀 트리플",
  "REPLAY": "리플레이",
  "watching ": "보는 중 ", // 아래로
  " play ": " 님이 플레이하는 ", // 아래로
  "finesse piece": "개의 피네스 블록", // 충돌 가능?
  "finesse pieces": "개의 피네스 블록", // 충돌 가능?
  "only the first 100 are shown. to see the full leaderboard, click VIEW FULL above.": "처음 100개만 표시돼요. 전체 순위표를 보려면 위의 전체 보기를 클릭하세요.",
  "top the global leaderboards!": "전 세계 순위표에서 정상을 차지하세요!",
  "TETRA CHANNEL / LEADERBOARDS": "테트라 채널 / 리더보드",
  "TETRA CHANNEL / PLAYERS": "테트라 채널 / 플레이어",
  "TETRA CHANNEL / ME": "테트라 채널 / 나",
  "BY LEAGUE RATING": "리그 레이팅을 기준으로",
  "BY XP": "경험치를 기준으로",
  "fetching players…": "플레이어 불러오는 중…",
  "glicko: ": "글리코: ",
  "email (optional)": "이메일 (선택)",
  "PASSWORD AGAIN": "비밀번호 확인",
  "REGISTER": "등록하기",
  "username must be 3-16 characters long and only consist of letters, numbers, dashes and underscores": "닉네임은 3-16자 길이여야 하고 문자, 숫자, 대시, 밑줄로만 구성돼 있어야 해요.",
  "forgot your password?": "비밀번호를 잊어버리셨나요?",
  "if you have an email address associated with your account, you can reset your password by entering your email.": "계정에 연결된 이메일 주소가 있는 경우 이메일을 입력해 비밀번호를 재설정할 수 있어요.",
  "you must enter a valid email address": "유효한 이메일 주소를 입력해야 해요",
  "email": "이메일",
  "REQUEST RESET": "초기화 요청하기",
  "WHAT'S NEW": "변경 사항",
  "ALL PATCH NOTES": "모든 패치 노트 보기",
  "COOL!": "좋네요!",
  "welcome back to TETR.IO!": "TETR.IO에 다시 오신 걸 환영해요!",
  "LOG OUT": "로그아웃",
  "is this you?": "이 닉네임이 맞나요?",
  "MULTIPLAYER": "멀티플레이어",
  "play online with friends and foes": "친구랑 적과 온라인으로 플레이하세요",
  "SOLO": "솔로",
  "HOME": "홈",
  "challenge yourself and top the leaderboards": "자신에게 도전하고 리더보드 정상을 차지하세요",
  "leaderboards, replays and more": "리더보드, 리플레이, 그리고 더",
  "CONFIG": "설정",
  "connected to server": "서버에 연결됐어요",
  "enter room id or url and hit enter...": "방 ID 또는 링크를 입력하고 enter를 누르세요...",
  "TETRA LEAGUE": "테트라 리그",
  "PEOPLE": "피플",
  "In Menus ": "메뉴 화면 ",
  "Ǖ find someone…": "Ǖ 누군가를 찾으세요…",
  "YOU ARE SILENCED": "침묵 제재 상태예요",
  "Stop spamming or you will be silenced!": "도배를 멈추세요! 계속 도배하면 침묵 제재 상태가 돼요!",
  " ONLINE": " 온라인",
  "appear as usual": "평소와 같이 표시",
  " AWAY": " 자리 비움",
  "appear away, unless you're offline or busy": "오프라인이거나 바쁨 상태가 아닌 한 자리 비움 상태로 표시",
  " BUSY": " 바쁨",
  "appear busy, unless you're offline. receive no notifications. always enabled in TETRA LEAGUE (unless you're invisible)": "오프라인 상태가 아닌 한 바쁨 상태로 표시. 알림을 받지 않음. 테트라 리그에서는 항상 활성화됨(오프라인 표시 상태가 아닌 한)",
  " INVISIBLE": " 오프라인 표시",
  "appear offline at all times": "항상 오프라인 상태로 표시",
  "ONLINE": "온라인",
  "ALL": "전체",
  "OTHER": "기타",
  "BLOCKED": "차단됨",
  "Nobody's online right now.": "지금은 아무도 온라인 상태가 아니예요.",
  "Not connected to online servers. Sit tight, we'll try to reconnect you in the background.": "온라인 서버에 연결되지 않았어요. 잠시만 기다려 주세요. 백그라운드에서 다시 연결해 볼게요.",
  "Notifications will appear here.": "알림은 여기에 표시돼요.",
  "You haven't added any friends yet. Click the FRIEND button on a profile to friend them.": "아직 아무 친구도 추가하지 않았어요. 프로필에서 친구 버튼을 클릭해서 친구로 추가하세요.", // 볼드 필요
  "If someone outside of your friends list messages you, they'll appear here.": "친구 목록에 없는 사람이 내게 메시지를 보내면 여기에 표시돼요.",
  "You haven't blocked anyone yet.": "아직 차단한 사람이 없어요.",
  "NOTIFICATIONS": "알림",
  "You forfeited a ranked match": "랭크 경기에서 기권패했어요",
  "You have been awarded a loss for this match. Please ensure you have the time and internet connection to play! Repeated forfeits are punished (and will be automatically punished in the future). Thank you for understanding!": "이 경기에서 패배 처리됐어요. 플레이할 수 있는 시간이 있는지, 인터넷 연결이 가능한지 확인해 주세요! 반복적인 기권패는 처벌을 받게 되며, 향후에도 자동으로 처벌을 받게 돼요. 이해해 주셔서 고마워요!",
  "pick a game mode": "게임 모드를 고르세요",
  "fight players of your skill in ranked duels": "랭크 경기에서 실력이 비슷한 플레이어와 싸워 보세요",
  "QUICK PLAY": "빠른 플레이",
  "jump into a currently ongoing match": "현재 진행 중인 경기로 뛰어들어가 보세요",
  "CUSTOM GAME": "사용자 지정 게임",
  "create public and private rooms to play by your rules": "규칙에 따라 플레이할 수 있는 공용 방과 개인 방을 만드세요",
  "ROOM LISTING": "방 목록",
  "join public custom games": "공개 사용자 지정 게임에 참여하세요",
  " - games won: ": " - 이긴 판 수: ", // 미적용
  "FINDING MATCH": "경기 찾는 중",
  "MATCH FOUND": "경기 찾음",
  "JOINING MATCH": "매치 참여 중",
  "FT3": "3선승",
  "FT5": "5선승",
  "FT7": "7선승",
  ", round ": ", 라운드 ",
  "FINISH!": "종료!",
  "MATCH POINT": "매치 포인트",
  "TIEBREAKER": "타이브레이커",
  "TETRA LEAGUE FT3": "테트라 리그 3선승제",
  "TETRA LEAGUE FT5": "테트라 리그 5선승제",
  "TETRA LEAGUE FT7": "테트라 리그 7선승제",
  "IN QUEUE -": "개의 대기열 -",
  "IN GAME": "게임 중",
  "estimated queue time:": "예상 대기 시간:",
  "SECONDS": "초",
  "ENTER MATCHMAKING": "매치 메이킹 참가",
  "LEAVING EARLY IS PUNISHED": "빠른 탈주는 처벌받아요",
  "HOW DOES IT WORK?": "어떻게 작동하죠?",
  "Ǳ LEADERBOARDS": "Ǳ 리더보드",
  "enter matchmaking and you will be matched up with a player of similar skill in a game of 1v1 VERSUS.": "매치 메이킹에 들어가면 비슷한 실력의 플레이어와 1대1 대결을 펼치게 돼요.", // 미적용
  "win games to gain TR and rank up! you must play at least 10 games to see your TR. to get a RANK and enter the GLOBAL LEADERBOARDS, keep playing consistently.": "게임에서 승리하여 TR을 획득하고 순위를 올리려면 최소 10판을 플레이해야 해요. 순위를 얻고 글로벌 리더보드에 진입하려면 꾸준히 플레이하세요.", // 미적용
  "if you leave the game early at any point, you will be awarded a loss. go conquer the ranks!": "어느 시점에서든 게임을 일찍 끝내면 패배해요. 순위를 정복하세요!", //미적용
  "face off against others and rise up through the ranks!": "다른 사람들과 대결하고 순위를 올리세요!",
  "switching server…": "서버 이동 중…", // 미적용
  "server switched": "서버 이동됨", //미적용
  "GAME IN PROGRESS, GOOD LUCK!": "게임 진행 중, 행운을 빌어요!",
  "PLAYERS (": "플레이어 (", // 미적용
  "CHAT": "채팅",
  "Please remember to be civil to your opponent.": "상대방에게 예의를 지켜야 한다는 점을 잊지 마세요.",
  "TETRA LEAGUE STANDING": "테트라 리그 순위",
  "TETRA LEAGUE / RESULTS": "테트라 리그 / 결과",
  "DEFEAT": "패배",
  "VICTORY": "승리",
  "Welcome to Quick Play chat! Please remember to be civil to your opponents - chat is actively monitored.": "빠른 플레이 채팅에 오신 것을 환영해요! 채팅은 적극적으로 모니터링되고 있으니 상대방에게 예의를 지켜야 한다는 점을 잊지 마세요.",
  "PUBLIC ROOM": "공개 방",
  "create a public room anyone can join": "누구나 참여할 수 있는 공개 방 만들기",
  "PRIVATE ROOM": "비공개 방",
  "create a private room for you and friends": "나와 친구들을 위한 비공개 방 만들기",
  "MULTIPLAYER / ROOM LISTING": "멀티플레이어 / 방 목록",
  "REFRESH": "새로고침",
  "anons allowed: ": "익명 허용: ", // 미적용
  ", unranked allowed: ": ", 무랭크 허용: ", // 미적용
  " INGAME - ": " 게임 중 - ", // 미적용
  " LOBBY -  ": " 로비 -  ", // 미적용
  " and below -  ": " 포함 그 이하 -  ", // 미적용
  "YES": "허용",
  "NO": "금지",
  "pick a room to join!": "참여할 방을 고르세요!",
  "CURRENTLY INGAME": "게임 진행 중", // 미적용
  "SPECTATE": "관전",
  "grid": "격자",
  "OR": "또는", // 미적용
  "ZEN": "젠",
  "EXIT": "나가기",
  "left the room": "님이 방을 나갔어요",
  "disconnected": "님의 연결이 끊어졌어요",
  "joined the room": "님이 방에 들어왔어요",
  "ANON": "익명",
  "40 LINES": "40줄",
  "complete 40 lines as quickly as possible": "최대한 빨리 40줄을 없애세요",
  "BLITZ": "블리츠",
  "a two-minute race against the clock": "시계에 맞서는 2분 간의 레이스",
  "get as many points as possible within 2 minutes!": "2분 안에 최대한 많은 점수를 획득하세요!",
  "clear lines to level up and gain more points and speed!": "줄을 없애 레벨을 올리고 더 많은 포인트와 속도를 얻으세요!",
  "TWO-MINUTE BLITZ": "2분 블리츠",
  "relax or train in this neverending mode": "무한 반복 모드에서 휴식하거나 훈련하세요",
  "CUSTOM": "사용자 지정",
  "play, train and experiment by your rules": "자신만의 규칙에 따라서 플레이, 훈련, 그리고 실험하세요",
  "welcome to TETRA CHANNEL!": "테트라 채널에 오신 걸 환영해요!",
  "enter replay id, url or username and hit enter...": "리플레이 ID, URL 또는 닉네임을 입력하고 enter를 누르세요...", // 미적용
  "VISIT THE TETRA CHANNEL SITE": "테트라 채널 사이트 방문",
  "VIEW FULL LEADERBOARDS, COUNTRY LEADERBOARDS, USER PAGES AND MORE": "전체 순위표, 국가 순위표, 사용자 페이지 등 보기",
  "LEADERBOARDS": "리더보드",
  "GLOBAL LEADERBOARDS FOR 40 LINES AND BLITZ": "40줄과 블리츠의 글로벌 리더보드",
  "ME": "나",
  "VIEW YOUR OWN RECORDS AND RECENT GAMES": "자신의 기록 및 최근 게임 보기",
  "PLAYERS": "플레이어",
  "TETRA LEAGUE LEADERBOARDS AND XP": "테트라 리그 리더보드와 XP",
  "LIVE NOW": "현재 라이브 중",
  "TETRA NEWS": "테트라 뉴스",
  "clear 40 lines in the shortest amount of time possible.": "최단 시간 내에 40줄을 없애세요.", // 미적용
  "score doesn't matter here, just go for the world record!": "점수는 중요하지 않으니, 세계 신기록에 도전하세요!", // 미적용
  "PERSONAL BEST": "최고 기록",
  "RANDOM": "랜덤",
  "pick a completely random BGM for me": "완전히 랜덤으로 배경 음악을 골라 주세요",
  "RANDOM: CALM": "랜덤: 잔잔",
  "pick a random calmer BGM for me": "랜덤으로 잔잔한 배경 음악을 골라 주세요",
  "RANDOM: BATTLE": "랜덤: 배틀",
  "pick a random intenser battle BGM for me": "랜덤으로 강렬한 배경 음악을 골라 주세요",
  "CHIKA - INTERFACE": "CHIKA - 인터페이스",
  "KAMIYA - INTERFACE": "KAMIYA - 인터페이스",
  "TAKAYUKI - INTERFACE": "TAKAYUKI - 인터페이스",
  "KAMOKING - INTERFACE": "KAMOKING - 인터페이스",
  "MIRERA - INTERFACE": "MIRERA - 인터페이스",
  "KVK - CALM": "KVK - 잔잔",
  "CHIKA - CALM": "CHIKA - 잔잔",
  "TAKAHASHI TAKASHI - CALM": "TAKAHASHI TAKASHI - 잔잔",
  "AKIKO SHIOYAMA - INTERFACE": "AKIKO SHIOYAMA - 인터페이스",
  "L-side - INTERFACE": "L-side - 인터페이스",
  "AIBA MAKOTO - CALM": "AIBA MAKOTO - 잔잔",
  "CHIKA - SPECIAL": "CHIKA - 특별",
  "FUJINAWA KAZUHIKO - INTERFACE": "FUJINAWA KAZUHIKO - 인터페이스",
  "OMEGANE - INTERFACE": "OMEGANE - 인터페이스",
  "KAMOKING - CALM": "KAMOKING - 잔잔",
  "MEESAN - CALM": "MEESAN - 잔잔",
  "KAMOKING - BATTLE": "KAMOKING - 배틀",
  "TOMOKI - BATTLE": "TOMOKI - 배틀",
  "AIBA MAKOTO - CALM": "AIBA MAKOTO - 잔잔",
  "MIKIYA KOMABA - BATTLE": "MIKIYA KOMABA - 배틀",
  "SUDO MIKADUKI - CALM": "SUDO MIKADUKI - 잔잔",
  "YOSHI - CALM": "YOSHI - 잔잔",
  "OMEGANE - CALM": "OMEGANE - 잔잔",
  "NOBUHAMU - CALM": "NOBUHAMU - 잔잔",
  "NAOKI HIRAI - CALM": "NAOKI HIRAI - 잔잔",
  "TSUTOMU - CALM": "TSUTOMU - 잔잔",
  "START": "시작",
  "OPTIONS": "옵션",
  "pro mode": "프로 모드",
  "alert on finesse fault": "피네스 실수 시 알림",
  "retry on finesse fault": "피네스 실수 시 재시작",
  "stride mode": "빨리빨리 모드",
  "ADVANCED": "고급",
  "press START to begin playing": "플레이하려면 시작을 누르세요", // 볼드 필요
  "play as you wish! replays are not submitted.": "원하는 대로 플레이하세요! 리플레이는 제출되지 않아요.",
  "EXPORT SETTINGS": "설정 내보내기",
  "lvl": "레벨", // 미적용
  "CLOSE": "닫기",
  "ago": " 전", // 미적용
  "GLOBAL": "세계",
  "COUNTRY": "국내",
  "Ǳ VIEW FULL PROFILE": "Ǳ 전체 프로필 보기",
  "SUPPORT TETR.IO": "TETR.IO 후원",
  "— osk, founder and developer of TETR.IO": "- osk, TETR.IO의 설립자 겸 개발자",
  "...or pick a custom length (up to 1200 months)": "...또는 사용자 지정 기간 선택(최대 1200개월까지)",
  "CUSTOM LENGTH": "사용자 지정 기간",
  "enter an amount of months (max: 1200)": "개월수를 입력하세요(최대: 1200)",
  "CANCEL": "취소",
  "SUBMIT": "제출",
  "SUPPORT!": "후원하기!",
  "Gift to other player(s)": "다른 플레이어(들)에게 선물하기",
  "will be converted to your local currency on payment": "결제 시 현지 통화로 변환돼요",
  "fetching TETRA LEAGUE data…": "테트라 리그 데이터 불러오는 중…",
  "connecting to live servers…": "실시간 서버 연결 중…",
  "RESET": "초기화",
  "OUT OF FOCUS": "초점 이탈됨",
  "click to return to TETR.IO": "TETR.IO로 돌아가려면 클릭하세요",
  "KEEP HOLDING TO RETRY": "재시도하려면 계속 누르고 있으세요",
  "KEEP HOLDING TO FORFEIT": "포기하려면 계속 누르고 있으세요",
  "RETRY": "재시도",
  "BACK TO TITLE": "타이틀 화면으로",
  "CLEAR 40 LINES!": "40줄을 없애세요!",
  "replay will not be saved": "리플레이는 저장되지 않아요",
  "USERNAME": "닉네임",
  "sfx": "효과",
  "bgm": "배경",
  "joining room…": "방 참여 중…",
  "FRIEND": "친구",
  "STARTING IN": "게임이 곧 시작돼요…",
  "Super Lobby Mode Engaged - congratulations on hitting 100 players! Joins and leaves will be suppressed, and the winner of games in this room will earn a special profile badge!": "슈퍼 로비 모드 적용 - 플레이어 100명 돌파를 축하해요! 입퇴장 메시지는 나오지 않으며, 이 방에서 게임을 승리한 플레이어는 특별한 프로필 배지를 획득할 수 있어요!",
  "Super Lobby Mode Disengaged": "슈퍼 로비 모드 해제",
  "message...": "메시지...",
  "PLAYING": "플레이 중", // 미적용
  "click to switch to SPECTATORS": "관전자로 바꾸려면 클릭하세요",
  "ROYALE KNOCKOUT": "로얄 녹아웃",
  "PM": "오후",
  "requesting account data…": "계정 데이터 요청 중…",
  "ACCOUNT": "계정",
  "change account settings": "계정 설정 변경",
  "hover over a setting for more info": "설정 위로 마우스를 올려 놓으면 더 많은 정보를 확인할 수 있어요",
  "CONTROLS": "조작",
  "HANDLING": "감도",
  "VOLUME & AUDIO": "볼륨 & 오디오",
  "GAMEPLAY": "게임플레이",
  "VIDEO & INTERFACE": "비디오 & 인터페이스",
  "CUSTOMIZATION": "커스터마이징",
  "VERSUS KNOCKOUT": "대결 녹아웃",
  "HOST": "방장",
  "Welcome to chat! Please remember to be civil to your opponents.": "채팅에 오신 것을 환영해요! 상대방에게 정중하게 대하는 것을 잊지 마세요.",
  "SAVE": "저장",
  "click to copy url": "링크를 복사하려면 클릭하세요",
  "this user is playing anonymously": "이 유저는 익명으로 플레이하고 있어요",
  "WELCOME": "환영",
  "ROOM": "방",
  "MATCH": "경기",
  "GAME": "게임",
  "loading SFX...": "효과음 로딩 중...",
  "runing benchmarks...": "벤치마크 실행 중...", // 적용 불확실
  "checking for game updates...": "게임 업데이트 확인 중...",
  "loading home banner data...": "홈 배너 데이터 로딩 중...",
  "GENERAL": "일반",
  "OBJECTIVE": "목표",
  "relax or train in a neverending mode! your progress is stored across games.": "무한 반복 모드에서 휴식을 취하거나 훈련하세요! 진행 상황은 게임 간에 저장돼요.",
  "adjust the feel or help train using the ZEN SIDEBAR.": "젠 사이드바를 사용하여 느낌을 조정하거나 훈련을 도우세요.",
  "you can undo and redo placements with CTRL+Z and CTRL+Y!": "CTRL+Z와 CTRL+Y로 배치를 취소하거나 재실행할 수 있어요!",
  "H": "시간",
  "THE TEAM": "팀",
  "FOUNDER & LEAD PRODUCER": "설립자 & 리드 프로듀서",
  "programming, graphics design, production, general development": "프로그래밍, 그패픽 디자인, 제작, 전반적인 개발",
  "your currently set keybinds are:": "현재 설정된 키 바인딩은:",
  "[NOT SET]": "[미설정]",
  "press any key or button": "아무 키나 버튼을 누르세요",
  "click anywhere to remove the keybind": "키 바인딩을 제거하려면 아무 곳이나 클릭하세요",
  "move falling piece left": "떨어지는 블록을 왼쪽으로 이동",
  "move falling piece right": "떨어지는 블록을 오른쪽으로 이동",
  "soft drop": "소프트 드롭",
  "hard drop": "하드 드롭",
  "rotate counterclockwise": "반시계 방향으로 회전",
  "rotate clockwise": "시계 방향으로 회전",
  "rotate 180": "180도 회전",
  "swap hold piece": "홀드한 블록으로 교체",
  "you can change these and many other settings in CONFIG.": "설정에서 이 설정과 기타 여러 설정을 바꿀 수 있어요.", // 볼드
  "click on the tabs above to explore and/or change room options as you wish. have fun!": "위의 탭을 클릭하여 원하는 대로 방 설정을 탐색하거나 변경하세요. 즐거운 시간 보내세요!",
  "GOT IT!": "이해했어요!",
  "room name": "방 이름",
  "room configuration updated!": "방 설정이 업데이트됐어요!",
  "room configuration updated partially": "방 설정이 부분적으로 업데이트됐어요",
  "presets must be ASCII characters. sorry!": "프리셋은 ASCII 문자여야 해요. 미안해요!",
  "room name must be ASCII characters. sorry!": "방 이름은 ASCII 문자여야 해요. 미안해요!",
  "unknown match gamemode": "알 수 없는 경기 게임모드",
  "unknown bag type": "알 수 없는 가방 유형",
  "unknown spin bonus type": "알 수 없는 스핀 보너스 종류",
  "unknown combo table": "알 수 없는 콤보 테이블",
  "unknown passthrough mode": "알 수 없는 통과 모드",
  "player limit": "플레이어 수 제한",
  "auto start": "자동 시작",
  "public room": "공개 방",
  "allow anonymous users to join": "익명 유저 참여 허용",
  "allow unranked users to play": "무랭크 유저 플레이 허용",
  "rank limit": "랭크 제한",
  "limit by top rank": "상위 랭크로 제한",
  "music": "음악",
  "gamemode": "게임 모드",
  // "versus": "대결",
  // "royale": "로얄",
  // "practice": "연습",
  "VERSUS": "대결",
  "[2 - ∞ players] great for 1v1 and small lobbies!": "[2 - ∞ 플레이어] 1대1과 소규모 로비에 적합!",
  "BATTLE ROYALE": "배틀로얄",
  "[2 - ∞ players] a full-fledged battle royale gamemode great for big lobbies!": "[2 - ∞ 플레이어] 대형 로비에 적합한 본격적인 배틀로얄 게임 모드!",
  "PRACTICE": "연습",
  "[2 players] great for live training with a friend! enables undoing and resetting your board": "[2 플레이어] 친구와 함께 라이브 훈련에 좋아요! 보드 취소 및 재설정 가능",
  "first to (FT)": "선승(FT)",
  "win by (WB)": "승차(WB)",
  "stock": "여분 목숨",
  "link copied!": "링크가 복사됐어요!",
  "replay link copied!": "리플레이 링크가 복사됐어요!",
  "EDIT": "편집",
  "THIS ACTION REQUIRES SUPPORTER": "이 작업에는 서포터가 필요해요",
  "game presets": "게임 프리셋",
  "random bag type": "랜덤 가방 유형",
  "allowed spins": "허용된 스핀",
  "T-SPINS": "T-스핀",
  "receive bonuses for spinning T-pieces": "T-블록을 회전시키면 보너스를 받아요",
  "ALL-SPIN": "올-스핀",
  //"all": "전체",
  "receive bonuses for spinning all pieces": "어떤 블록을 회전시켜도 보너스를 받아요",
  "HANDHELD": "경량화",
  //"handheld": "경량화",
  "receive bonuses for spinning all pieces BUT attacks are halved except for T-SPINS": "어떤 블럭을 회전시켜도 보너스를 받지만, T-스핀을 제외한 공격은 절반으로 줄어들어요",
  "recieve bonuses for spinning all pieces. non T-SPINS attacks are halved. pieces use 4-corner detection": "어떤 블록을 회전시켜도 보너스를 받아요. T-스핀이 아닌 공격은 절반으로 감소해요. 블록은 4-코너 감지를 사용해요",
  "STUPID": "댕청",
  //"stupid": "댕청",
  "everything is a spin because YEAH WHY NOT (O-spin SUPPORTED!)": "모든 것이 스핀이에요. 왜냐하면... 안 될 거 있나요(O-스핀 지원!)?",
  "receive no spin bonuses": "스핀 보너스를 받지 않아요",
  "combo table": "콤보 테이블",
  "NONE": "없음",
  //"none": "없음",
  "Disable combo chaining": "콤보 연쇄 비활성화",
  "MULTIPLIER": "멀티플라이어",
  //"multiplier": "멀티플라이어",
  "TETR.IO's combo multiplier": "TETR.IO의 콤보 멀티플라이어",
  "CLASSIC GUIDELINE": "클래식 가이드라인",
  //"classic guideline": "클래식 가이드라인",
  "classic guideline combo table": "클래식 가이드라인 콤보 테이블",
  "MODERN GUIDELINE": "모던 가이드라인",
  //"modern guideline": "모던 가이드라인",
  "modern guideline combo table": "모던 가이드라인 콤보 테이블",
  "allow 180 spins": "180도 회전 허용",
  "kick table": "킥 테이블",
  "bombs-style garbage": "폭탄전 스타일 쓰레기",
  "use hard drop": "하드 드롭 사용",
  "use NEXT queue": "넥스트 큐 사용",
  "use HOLD queue": "홀드 큐 사용",
  "next pieces": "다음 블록",
  "infinite movement": "무한한 움직임",
  "show shadow piece": "그림자 블록 보이기",
  "line clear ARE": "라인 클리어 ARE", // 검수 필요
  "enforce below handling settings": "아래 핸들링 설정 강제 적용",
  "GRAVITY & LEVELLING": "중력 & 레벨링",
  'use levelling (overrides "gravity")': '레벨링 사용 ("중력" 덮어씀)',
  "enforced ARR": "ARR 적용",
  "enforced DAS": "DAS 적용",
  "enforced SDF": "SDF 적용",
  "disable knockout": "녹아웃 비활성화",
  "board width": "보드 폭",
  "board height": "보드 높이",
  "GRAVITY & MARGIN TIME": "중력 & 마진 시간",
  "gravity": "중력",
  "gravity increase": "중력 증가량",
  "gravity margin time": "중력 마진 시간",
  "garbage multiplier": "쓰레기 승수",
  "garbage margin time": "쓰레기 마진 시간",
  "garbage increase": "쓰레기 증가량",
  "messiness on change": "변화에 따른 혼잡도",
  "messiness within attack": "공격 내 혼잡도",
  "avoid same column RNG": "동일 열 RNG 피하기",
  "messiness timeout": "혼잡도 타임아웃",
  "garbage cap increase": "쓰레기 상한 증가량",
  "garbage cap max": "최대 쓰레기 상한",
  "garbage absolute cap": "쓰레기 절대 상한",
  "garbage phase": "쓰레기 페이즈",
  "garbage target bonus": "쓰레기 타깃 보너스",
  "no bonus whatsoever": "보너스가 전혀 없어요",
  "DEFENSIVE": "수비적",
  "defensive": "수비적",
  "a bonus is added when defending incoming attacks": "들어오는 공격을 방어할 때 보너스가 추가돼요",
  "OFFENSIVE": "공격적",
  "offensive": "공격적",
  "a bonus is added to both defense and offence": "방어와 공격 모두에 보너스가 추가돼요",
  "garbage entry": "쓰레기 진입",
  "INSTANT": "즉각적",
  "instant": "즉각적",
  "garbage enters instantly": "쓰레기가 즉시 들어와요",
  "CONTINUOUS": "연속적",
  "continuous": "연속적",
  "garbage rolls in one by one": "쓰레기가 하나씩 굴러 들어와요",
  "DELAYED PIECE SPAWN": "블록 스폰 지연",
  "delayed": "지연",
  "garbage rolls in one by one but delays your next piece": "쓰레기가 하나씩 굴러 들어오지만 다음 블록이 지연돼요",
  "garbage are": "쓰레기 are",
  "garbage queue": "쓰레기 대기열",
  "garbage blocking": "쓰레기 블로킹",
  "COMBO BLOCKING": "콤보 블로킹",
  "combo blocking": "콤보 블로킹",
  "incoming garbage will be delayed and reduced on successive line clears": "줄을 연속으로 없애면 들어오는 쓰레기가 늦춰지고 감소해요",
  "LIMITED BLOCKING": "제한적 블로킹",
  "limited blocking": "제한적 블로킹",
  "incoming garbage can be reduced only once per next immediate piece": "들어오는 쓰레기를 바로 다음 블록당 한 번만 감소시킬 수 있어요",
  "incoming garbage cannot be blocked": "들어오는 쓰레기를 막을 수 없어요",
  "garbage passthrough": "쓰레기 통과",
  "ZERO": "제로",
  // "zero": "제로",
  "opposing attacks in transit always cancel eachother out": "이동 중인 상대방의 공격은 항상 서로 상쇄돼요",
  "LIMITED": "제한됨",
  // "limited": "제한됨",
  "opposing attacks in transit cancel out while garbage is flying": "쓰레기가 날아가는 동안 이동 중인 상대 공격이 상쇄돼요",
  "CONSISTENT": "지속적",
  // "consistent": "지속적",
  "opposing attacks in transit cancel out except when garbage is flying": "쓰레기가 날아가고 있는 경우를 제외하고 이동 중 상대인 공격은 상쇄돼요",
  // "full": "전체",
  "opposing attacks in transit do not cancel eachother out": "이동 중인 상대 공격은 서로 상쇄되지 않아요",
  "allow manual targeting": "수동 타기팅 허용",
  "enable back-to-back chaining": "백-투-백 체인 활성화",
  "enable all clears": "올 클리어 활성화",
  'use random seed (overrides "seed")': '랜덤 시드 사용하기("시드" 덮어씀)',
  "use master levels": "마스터 레벨 사용",
  "starting level": "시작 레벨",
  "level speed": "레벨 속력",
  'use static levelling (overrides "level speed")': '정적 레벨링 사용("레벨 속력" 덮어씀)',
  "level static speed": "레벨 정적 속력",
  "base gravity": "기본 중력",
  "lock delay": "잠금 딜레이",
  "seed": "시드",
  "allow retry": "재시도 허용",
  "enable clutch clears": "클러치 클리어 활성화",
  "disable lockout": "록아웃 비활성화",
  "SURVIVAL": "생존",
  "mode": "모드",
  "do not spawn any garbage": "어떤 쓰레기도 생성하지 않음",
  "LAYER": "레이어",
  "keep a layer of garbage on the board": "보드에 쓰레기 레이어 유지",
  "TIMER": "타이머",
  "spawn garbage on a timer": "타이머를 기준으로 쓰레기 생성",
  "garbage messiness %": "쓰레기 혼잡도 %",
  "garbage travel speed": "쓰레기 이동 속도",
  "garbage cap": "쓰레기 상한",
  "layer height": "레이어 높이",
  "sticky layer": "끈적끈적한 레이어",
  "minimum layer height": "최소 레이어 높이",
  "timer interval": "타이머 간격",
  "key": "기준",
  "final score will be displayed": "최종 점수가 표시돼요",
  "final time will be displayed": "최종 시간이 표시돼요",
  "final line count will be displayed": "최종 줄 수가 표시돼요",
  "objective": "목표",
  "play infinitely": "무한으로 즐겨요",
  "get to a set amount of lines to clear": "정해진 수의 줄에 도달해 클리어",
  "TIMED": "시간",
  "timed": "시간",
  "play for a set amount of time to clear": "정해진 시간 동안 플레이하여 클리어",
  "get to a set amount of garbage lines to clear": "정해진 수의 쓰레기에 도달해 클리어",
  "count": "수", // 검수 필요
  "time": "시간",
  "score": "점수",
  "timed": "시간",
  "lines": "줄",
  "FINAL LINE COUNT": "최종 줄 수",
  "topping out is OK": "톱 아웃은 괜찮아요",
  "display objective behind board": "보드 뒤에 목표 표시",
  "META": "메타",
  "INTRO": "인트로",
  "mission": "미션",
  "play countdown": "카운트다운 재생",
  "countdown count": "카운트다운 횟수",
  "countdown interval": "카운트다운 간격",
  "time before countdown": "카운트다운 전 시간",
  "time before start": "시작 전 시간",
  "zoom animation": "확대/축소 애니메이션",
  "NO ANIMATION": "애니메이션 없음",
  "display no animation": "애니메이션 표시 안 함",
  "fast": "빠름",
  "display a fast animation": "빠른 애니메이션 표시",
  "slow": "느림",
  "display a slow animation": "느린 애니메이션 표시",
  "CINEMATIC": "시네마틱",
  "cinematic": "시네마틱",
  "display a very slow animation": "매우 느린 애니메이션 표시",
  "COUNTERS": "카운터",
  "left counter slot 1": "왼쪽 카운터 슬롯 1",
  "left counter slot 2": "왼쪽 카운터 슬롯 2",
  "left counter slot 3": "왼쪽 카운터 슬롯 3",
  "left counter slot 4": "왼쪽 카운터 슬롯 4",
  "right counter slot": "오른쪽 카운터 슬롯",
  "EMPTY": "비워 두기",
  "---empty---": "---비어 있음---",
  "leave this slot empty": "이 슬롯을 비워 둠",
  "display the score in this slot": "이 슬롯에 점수 표시",
  "SCORE (per piece)": "(블록당) 점수",
  "spp": "spp",
  "display the score and score per piece in this slot": "이 슬롯에 점수와 블록당 점수 표시",
  "STOPWATCH": "스톱워치",
  "stopwatch": "스톱워치",
  "display the time passed in this slot": "이 슬롯에 경과 시간 표시",
  "timer": "타이머",
  "display the time remaining in this slot (for TIMED objective)": "이 슬롯에 남은 시간 표시(시간 목표인 경우)",
  "display the amount of cleared lines in this slot": "이 슬롯에 없앤 줄의 수 표시",
  "level": "레벨",
  "display the current level in this slot": "이 슬롯에 현재 레벨 표시",
  "PIECES": "블록",
  "pieces": "블록",
  "display the amount of placed pieces and speed in this slot": "이 슬롯에 놓은 블록의 수과 속력 표시",
  "INPUTS": "입력",
  "keys": "키",
  "display the amount of buttonpresses in this slot": "이 슬롯에 버튼 누름 횟수 표시",
  "HOLD": "홀드",
  "hold": "홀드",
  "display the amount of held pieces in this slot": "이 슬롯에 홀드한 블록의 수 표시",
  "allclears": "올클리어",
  "display the amount of ALL CLEARS in this slot": "이 슬롯에 올 클리어 수 표시",
  "GARBAGE CLEARED": "없앤 쓰레기",
  "garbage": "쓰레기",
  "display the amount of garbage lines cleared in this slot": "이 슬롯에 없앤 쓰레기 줄 수 표시",
  "enforce absolute line count": "절대적인 줄 수 강제 적용",
  "display progress bar": "진행률 바 표시",
  "GAME OVER": "게임 오버",
  "END RESULT": "종료 결과",
  "global rank": "글로벌 순위",
  "personal rank": "개인 순위",
  "PERSONAL BEST!": "개인 최고 기록!",
  "PERSONAL BEST": "개인 최고 기록",
  "WORLD RECORD!": "세계 신기록!",
  "spins": "스핀",
  "spin minis": "스핀 미니",
  "spin mini singles": "스핀 미니 싱글",
  "spin singles": "스핀 싱글",
  "spin mini doubles": "스핀 미니 더블",
  "spin doubles": "스핀 더블",
  "spin triples": "스핀 트리플",
  "spin quads": "스핀 쿼드",
  "AGAIN": "다시하기",
  "GLOBAL MODERATION & COMMUNITY MANAGEMENT TEAM": "글로벌 운영 & 커뮤니티 관리 팀",
  "MUSIC BY": "음악",
  "DEFAULT WALLPAPERS PROVIDED BY": "기본 배경화면 제공",
  "THIRD-PARTY TECHNOLOGIES (": "서드 파티 기술(",
  "SPECIAL THANKS": "특별한 감사",
  "THANK YOU FOR PLAYING.": "플레이해 주셔서 고마워요.",
  "TETR.IO, THE TETR.IO LOGO, TETRA LEAGUE, OSK, AND THE OSK LOGO ARE TRADEMARKS OF OSK.": "TETR.IO, TETR.IO 로고, 테트라 리그, OSK, 그리고 OSK 로그는 OSK의 상표입니다.",
  "ALL OTHER TRADEMARKS ARE THE PROPERTY OF THEIR RESPECTIVE OWNERS, TRADEMARK FAIR USE DOCTRINES APPLY.": "기타 모든 상표는 해당 소유자의 자산이며 상표 공정이용 원칙이 적용됩니다.",
  "VIEW ALL": "전체 보기",
  "GLOBAL MODERATOR": "글로벌 운영자",
  "ADMINISTRATOR": "관리자",
  "community moderator": "커뮤니티 운영자",
  "assisting global moderator": "글로벌 운영자 보조",
  "PROGRAMMING": "프로그래밍",
  "AUDIO, MUSIC, PROGRAMMING": "오디오, 음악, 프로그래밍",
  "assisting PROGRAMMING": "프로그래밍 보조",
  "GAME DESIGN": "게임 디자인",
  "assisting GRAPHICS DESIGN": "그래픽 디자인 보조",
  "forfeit game": "게임 기권",
  "retry game": "게임 재시도",
  "open chat": "채팅 열기",
  "pick targeting strategy": "타기팅 전략 고르기",
  "move in menus": "메뉴 내에서 이동",
  "confirm in menus": "메뉴 내에서 결정",
  "open social overlay": "소셜 오버레이 열기",
  "back in menus": "메뉴로 돌아가기",
  "controllers can be set up in CUSTOM controls - just press the controller buttons you wish to bind.": "컨트롤러는 사용자 지정 컨트롤에서 설정할 수 있고, 할당하려는 컨트롤러 버튼을 누르기만 하면 돼요.",
  "controller sensitivity": "컨트롤러 감도",
  "vibration intensity": "진동 강도",
  "GUIDELINE": "가이드라인",
  "LOW": "낮음",
  "HIGH": "높음",
  "WEAK": "약함",
  "STRONG": "강함",
  "SLOW": "느림",
  "FAST": "빠름",
  "prevent accidental hard drops": "우발적인 하드 드롭 방지",
  "cancel DAS when changing directions": "방향 변경 시 DAS 캔슬",
  "prefer soft drop over movement": "이동보다 소프트 드롭 우선시",
  "MUSIC": "음악",
  "QUIET": "조용함",
  "LOUD": "시끄러움",
  "SFX": "효과음",
  "stereo": "스테레오",
  "NO STEREO": "스테레오 없음",
  "SUPER STEREO": "극한의 스테레오",
  "MUTE": "음소거",
  "scroll to change volume": "스크롤로 볼륨 변경",
  "mute music when hidden": "숨겨져 있을 때 음악 음소거",
  "hear next pieces": "다음 블록 듣기",
  "hear other players": "다른 플레이어들 듣기",
  "hear attacks": "공격 듣기",
  "do not reset music when retrying": "재시도 시 음악 초기화하지 않기",
  "disable sound entirely": "소리 통째로 비활성화하기",
  "TEST": "테스트",
  "TWEAK MUSIC": "음악 조정",
  "ACTION TEXT": "액션 텍스트",
  "ON": "켬",
  "OFF": "끔",
  "SOME": "몇몇만",
  "board bounciness": "보드 탄력성",
  "STIFF": "빳빳함",
  "BOUNCY": "탱탱함",
  "damage shakiness": "대미지 흔들림",
  "SHAKY": "흔들림",
  "grid visibility": "격자 가시성",
  "TRANSPARENT": "투명함",
  "OPAQUE": "불투명함",
  "spectating": "관전 중",
  "board visibility": "보드 가시성",
  "shadow visibility": "그림자 가시성",
  "board zoom": "보드 확대/축소",
  "FAR": "멂",
  "NEAR": "가까움",
  "show duels side-by-side": "결투 나란히 보기",
  "spin board when you T-spin": "T-스핀 시 보드 회전하기",
  "alert me when i KO someone": "내가 누군가를 KO하면 알림 표시하기",
  "enable the fire meter": "파이어 미터 활성화하기",
  "warn me when i'm in danger": "내가 위험에 처했을 때 경고하기",
  "colored shadow piece": "블록 그림자 컬러로 표시",
  "gray out locked HOLD piece": "홀드한 블록이 잠기면 회색으로 표시",
  "GRAPHICS": "그래픽",
  "MINIMAL": "최소",
  "MEDIUM": "중간",
  "ULTRA": "울트라",
  "CACHING": "캐싱",
  "BALANCED": "균형적으로",
  "AGGRESSIVE": "공격적으로",
  "WEBGL MODE": "WEBGL 모드",
  "LEGACY": "레거시",
  "particle count": "파티클 개수",
  "FEW": "적게",
  "LOTS": "많게",
  "background visibility": "배경 가시성",
  "you just created an online game - you can start the game once two players are in the room (and not spectating)!": "방금 온라인 게임을 만들었어요 - (관전하지 않는) 두 명의 플레이어가 방에 있으면 게임을 시작할 수 있어요!",
  "you just joined an online game - the game will start whenever the HOST presses START. good luck!": "방금 온라인 게임에 참여했어요 - 방장이 언제든 시작을 누르면 게임이 시작돼요. 행운을 빌어요!",
  "you just joined an online game - the HOST can start the game once two players are in the room (and not spectating)!": "방금 온라인 게임에 참여했어요 - (관전하지 않는) 두 명의 플레이어가 방에 있으면 방장이 게임을 시작할 수 있어요!",
  "you just created an online game - the game will start whenever you press START. good luck!": "방금 온라인 게임을 만들었어요 - 언제든 시작을 누르면 게임이 시작돼요. 행운을 빌어요!",
  "render at a low resolution": "낮은 해상도에서 렌더링하기",
  "less precision on counters": "카운터 정밀도 낮게",
  "always simplify multiplayer thumbnails": "항상 멀티플레이어 썸네일 간소화하기",
  "do not animate background in super lobbies": "슈퍼 로비에서 배경화면 애니메이션 끄기",
  "no background in menus": "메뉴에서 배경화면 끄기",
  "filter profanity in chat": "채팅에서 비속어 필터링하기",
  "hide chat when ingame": "게임 중 채팅 숨기기",
  "hide room IDs": "방 ID 숨기기",
  "show emotes in chat": "채팅에서 이모지 보이기",
  "show animated emotes in chat": "채팅에서 애니메이션 이모지 보이기",
  "invert chat colors": "채팅 색상 반전하기",
  "darken screen behind chat": "채팅 뒤 화면 어둡게 하기",
  "keep replay tools open": "리플레이 툴 계속 열어 두기",
  "hide network warning icons": "네트워크 경고 아이콘 숨기기",
  "warn me when the game is not focused": "게임 초점 이탈 시 경고받기",
  "show the welcome guide": "웰컴 가이드 보이기",
  "use custom background image": "사용자 지정 배경화면 사용하기",
  "background URL (use multiple by separating with commas, confirm with ENTER)": "배경화면 링크(쉼표로 구분하여 여러 개 사용, ENTER로 확인)",
  "show desktop notifications": "데스크톱 알림 표시",
  "suppress notifications while ingame": "게임 중 알림 표시 안 함",
  "always play notification sounds at full volume": "항상 최대 볼륨으로 알림 소리 재생",
  "NOTIFY ME WHEN A FRIEND GOES ONLINE": "친구가 온라인 상태가 되면 알림",
  "NOTIFY ME WHEN A FRIEND GOES OFFLINE": "친구가 오프라인 상태가 되면 알림",
  "NOTIFY ME WHEN A FRIEND SENDS ME A DIRECT MESSAGE": "친구가 내게 쪽지를 보내면 알림",
  "NOTIFY ME WHEN A NON-FRIEND SENDS ME A DIRECT MESSAGE": "친구가 아닌 사람이 내게 쪽지를 보내면 알림",
  "NOTIFY ME WHEN SOMEONE INVITES ME TO A ROOM": "누군가 나를 방에 초대하면 알림",
  "OTHER NOTIFICATIONS": "기타 알림",
  "INGAME": "인게임",
  "INGAME & DESKTOP": "인게임 & 데스크톱",
  "targeting strategy even": "타겟팅 전략 균등",
  "targeting strategy eliminations": "타겟팅 전략 처치",
  "targeting strategy random": "타겟팅 전략 랜덤",
  "targeting strategy payback": "타겟팅 전략 복수",
  "menus: up": "메뉴: 위로",
  "menus: down": "메뉴: 아래로",
  "menus: left": "메뉴: 왼쪽으로",
  "menus: right": "메뉴: 오른쪽으로",
  "menus: confirm": "메뉴: 결정",
  "menus: back": "메뉴: 뒤로가기",
  "GO!": "시작!",
  "even": "균등",
  "elims": "처치",
  "random": "랜덤",
  "payback": "복수",
  "started the game": "게임이 시작됐어요",
  "you ko'd yourself": "자기 자신에게 처치 당함",
  "POINTS": "점수",
  "LINES RECEIVED": "줄 받음",
  "LINES SENT": "줄 보냄",
  "RESULTS": "결과",
  "game submitted!": "게임이 제출되었어요!",
  "NEXT": "다음",
  "the results are in!": "결과가 나왔어요!",
  "kick": "추방",
  "ban": "밴",
  "move to players": "플레이어로 이동",
  "move to spectators": "관전자로 이동",
  "transfer ownership": "방장 넘기기",
  "joining room": "방 참여",
  "you are now host of this room!": "이제 이 방의 방장이 됐어요!",
  "you were moved to spectators for being AFK": "자리 비움으로 인해 관전자로 이동됐어요",
  "SURVIVOR": "생존자",
  "ANONYMOUS": "익명",
  "SPECTATING": "관전 중",
  "click to switch to PLAYERS": "플레이어로 바꾸려면 클릭하세요",
  "[SYS]": "[시스템]",
  "game finished": "게임이 종료됐어요",
  "was kicked from the room": "님이 방에서 추방당했어요",
  "was banned from the room": "님이 방에서 밴 당했어요",
  "KICKED BY ROOM OWNER": "방장에 의해 추방당함",
  "you were kicked from the room by its owner.": "방장에 의해 방에서 추방당했어요.",
  "BANNED BY ROOM OWNER": "방장에 의해 밴 당함",
  "you were banned from the room by its owner.": "방장에 의해 방에서 밴 당했어요.",
  "you are banned from this room. please try again later, or ask the host to unban you with /unban": "이 방에서 밴 당하셨어요. 나중에 다시 시도하거나 방장에게 /unban으로 차단 해제를 요청하세요.",
  "[CMD]": "[명령]",
  "WINNER!": "우승자!",
  "GAME!": "게임 끝!",
  "leaving room...": "방 나가는 중...",
  "Ǿ SAVE REPLAY": "Ǿ 리플레이 저장",
  "ALIVE": "생존 시간",
  "you can change these and many other settings in CONFIG. have fun!": "설정에서 이런 설정과 다른 많은 설정을 변경할 수 있어요. 즐거운 시간 되세요!",
  "hover for more info!": "더 많은 정보를 원하신다면 마우스를 올려 놓으세요!",
  "you just joined QUICK PLAY - you will play in the next game in this lobby. please wait for the current game to finish. feel free to spectate or play ZEN while waiting!": "방금 빠른 플레이에 참여했어요 - 이 로비에서 다음 게임을 플레이하게 될 거예요. 현재 게임이 끝날 때까지 기다려 주세요. 기다리는 동안 자유롭게 관전하거나 젠을 플레이하세요!",
  "you just joined QUICK PLAY - the next game will start automatically. please wait just a moment longer!": "방금 빠른 플레이에 참여했어요 - 다음 게임이 자동으로 시작될 거예요. 조금만 더 기다려주세요!",
  "OK": "확인",
  "disconnected from server": "서버로부터 연결 해제됐어요",
  "CONNECTION ERROR": "연결 오류",
  "the server has disconnected you.": "서버가 연결을 끊었어요.",
  "please check your internet connection and configuration.": "인터넷 연결 및 설정을 확인하세요.",
  "due to browser limitations, tabbing out of TETR.IO midgame may cause disconnects.": "브라우저 제한으로 인해 TETR.IO를 게임 중간에 탭으로 나가면 연결이 끊어질 수 있어요.",
  // " VS ": " 대 ",
  "opponent forfeited": "상대 기권함",
  "no such room": "그런 방 없음",
  "ANONYMOUS USERS CANNOT EDIT THEIR ACCOUNTS": "익명 유저는 계정을 편집할 수 없어요", // 미적용, data-block-reason
  "the username ": "닉네임 ",
  " is registered. please enter your password to log in": "은(는) 등록돼 있어요. 로그인하려면 비밀번호를 입력하세요",
  "MISC": "기타",
  "LEVELING": "레벨링",
  "INFINITE HOLD": "무한 홀드",
  "SPINS": "스핀",
  "COMBO TABLE": "콤보 테이블",
  "KICK TABLE": "킥 테이블",
  "GRAVITY": "중력",
  "DISPLAY": "화면",
  "GARBAGE": "쓰레기",
  "custom": "사용자 지정",
  "DEFAULT": "기본",
  "default": "기본",
  "TETR.IO's premier room settings. optimized for battles with small groups or duels against friends and foes alike!": "TETR.IO 최고의 방 설정. 소규모 그룹의 전투나 친구 및 적과의 배틀에 최적화돼 있어요!",
  "tetra league": "테트라 리그",
  "settings copied directly from TETR.IO's matchmaking rooms! margin times and match goals are shifted slightly with duels in mind.": "TETR.IO의 매치 메이킹 방에서 직접 복사해 온 설정이에요! 결투를 염두에 두고 마진 시간과 매치 목표를 살짝 바꿨어요.",
  "ENFORCED DELAYS": "강제 딜레이",
  "enforced delays": "강제 딜레이",
  "this preset introduces several forms of enforced handling which introduces a generous skill ceiling! puts a focus on efficient and consistent play, as opposed to deafeningly fast rounds.": "이 프리셋은 다양한 형태의 강제적인 핸들링을 도입하여 넉넉한 스킬 상한선을 제공해요! 귀청이 찢어질 듯한 빠른 라운드보다는, 효율적이고 일관된 플레이에 중점을 두고 있어요.",
  "4-WIDE": "4-와이드",
  "4wide": "4와이드",
  "this party-focused preset uses a nonstandard board size which allows you to infinitely combo.": "파티에 초점을 맞춘 이 프리셋은 무한한 콤보를 가능하게 하는 비표준 보드 크기를 사용해요.",
  "100 BATTLE ROYALE": "100인 배틀로얄",
  "100 battle royale": "100인 배틀로얄",
  "this preset is similar to the BATTLE ROYALE gamemode but at a slower pace.": "이 프리셋은 배틀로얄 게임 모드와 비슷하지만 좀 더 속도가 느려요.",
  "CLASSIC": "클래식",
  //"classic": "클래식",
  "an endurance-focused challenge of pure stacking intellect! almost every value is changed to imitate stacker games made many years ago.": "순수 스태킹 능력을 시험하는 지구력 챌린지! 수년 전에 만들어진 스태커 게임을 모방하기 위해 거의 모든 값을 바꿨어요.",
  "ARCADE": "아케이드",
  "arcade": "아케이드",
  "featuring innovative mechanics created for a popular stacker found in arcades, this preset puts a focus on smart stacking and mastery with its custom kick table!": "오락실에서 인기 있는 스태커를 위해 만들어진 혁신적인 메커니즘을 토대로, 이 프리셋은 맞춤형 킥 테이블을 통해 똑똑한 스태킹과 실력에 중점을 두고 있어요!",
  "BOMBS": "폭탄전",
  "bombs": "폭탄전",
  "versus with an explosive twist! stack pieces on top of garbage to clear it and send devastating attacks to your opponents!": "폭발적인 반전이 있는 대전 모드! 쓰레기 위에 블록을 쌓아 없애고 상대에게 파괴적인 공격을 날리세요!",
  "LEGACY QUICK PLAY": "(구) 빠른 플레이",
  "quickplay": "빠른 플레이",
  "this legacy preset emulates TETR.IO's QUICK PLAY experience pre 6.4.0": "이 레거시 프리셋은 TETR.IO의 6.4.0 이전 빠른 플레이 경험을 구현했어요",
  "7-BAG": "7-백",
  //"7-bag": "7-백",
  "keep shuffling a bag of the 7 tetrominoes": "7개 테트라미노의 가방 하나를 계속 섞어요",
  "14-BAG": "14-백",
  //"14-bag": "14-백",
  "keep shuffling a bag of 2x the 7 tetrominoes": "7개 테트로미노가 2배 들어 있는 가방 하나를 계속 섞어요",
  "7+1-BAG": "7+1-백",
  //"7+1-bag": "7+1-백",
  "keep shuffling a bag of the 7 tetrominoes with one random extra tetromino": "7개 테트로미노의 가방 하나를 한 개의 랜덤한 여분 테트로미노와 계속 섞어요",
  "7+2-BAG": "7+2-백",
  //"7+2-bag": "7+2-백",
    "keep shuffling a bag of the 7 tetrominoes with two random extra tetrominoes": "7개 테트로미노의 가방 하나를 두 개의 랜덤한 여분 테트로미노와 계속 섞어요",
  "7+X-BAG": "7+X-백",
  //"7+x-bag": "7+x-백",
  "keep shuffling a bag of the 7 tetrominoes. the first few bags contain a few extras.": "7개 테트로미노의 가방 하나를 계속 섞어요. 처음 몇 가방에는 몇 개의 여분이 들어 있어요.",
  "random with repetition protection": "반복을 방지한 랜덤이에요",
  "PAIRS": "쌍",
  //"pairs": "쌍",
  "alternate between 2 tetrominoes": "2개의 테트로미노를 번갈아 가며 섞어요",
  "TOTAL MAYHEM": "총체적 난국",
  //"total mayhem": "총체적 난국",
  "completely random generation": "완전히 랜덤하게 생성돼요",
};

/**
 * @type {[string, RegExp, string][]}
 */
const SELECTOR_TRANSLATIONS = [
  ["#footer_text", /welcome to (.*?)!/, "$1에 오신 걸 환영해요!"],
  ["#sig_config > p", /tweak your&nbsp;(.*?)&nbsp;experience/, "$1 경험을 조정하세요"],
  ["#sig_about > p", /all about&nbsp;<span class="cheeky">(.*?)<\/span>(.*)/, "<span class=\"cheeky\">$1</span>$2에 관한 모든 것"],
  ["#footer_text", /tweak your settings for a better (.*?) experience/, "더 나은 $1 경험을 위해 설정을 조정하세요"],
  ["#config_export > p", /download a .TTC file of your config you can drag into&nbsp;(.*?)&nbsp;to import/, "$1에 드래그해 가져올 수 있는 .TTC 설정 파일 내려받기"],
  ["#video_powersave", /make&nbsp;(.*?)&nbsp;run slowly to keep other programs running smoothly/, "다른 프로그램이 부드럽게 돌아가도록 $1 느리게 실행하기"],
  ["#sys_guide > h2", /welcome to&nbsp;(.*?)!/, "$1에 오신 걸 환영해요!"],
  [".scroller_block > h2", /welcome to&nbsp;(.*?)!/, "$1에 오신 걸 환영해요!"],
  ["#sys_guide > p", /(.*?)&nbsp;is a free familiar yet fast-paced online stacker in the same genre as tetris, and played by millions across the globe./, "$1는 테트리스와 같은 장르의 친숙하면서도 빠르게 진행되는 무료 온라인 스태커 게임으로, 전 세계 수백만 명이 즐기고 있어요."],
  [".scroller_block > p", /(.*?)&nbsp;is a free-to-win familiar yet fast-paced online stacker in the same genre as tetris, and played by millions across the globe./, "$1는 전 세계 수백만 명이 플레이하고 있는, 무료로 즐길 수 있는 테트리스와 같은 장르의 친숙하면서도 빠르게 진행되는 온라인 스태커 게임이에요."],
  ["#footer_text", /thank you for playing (.*?)!/, "$1를 플레이해 주셔서 고마워요!"],
  ["#a.electron_jump_also.ns", /get&nbsp;(.*?)&nbsp;DESKTOP/, "$1 데스크톱 받기"], // 왜 안 될까?
  ["#div.electron_jump.ns", /open in&nbsp;(.*?)&nbsp;DESKTOP/, "$1 데스크톱에서 열기"], // 왜 안 될까?
  ["#about_desktop > h1", /(.*?)&nbsp;DESKTOP/, "$1 데스크톱"],
]

// CSS 폰트 적용
const fontFace = `
  @font-face {
    font-family: 'BMHANNAAir';
    src: url('https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.0/BMHANNAAir.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
        font-family: 'D2Coding';
        src: url('https://fastly.jsdelivr.net/gh/projectnoonnu/noonfonts_three@1.0/D2Coding.woff') format('woff');
        font-weight: normal;
        font-style: normal;
  }

  @import url("https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css");
`;

const style = document.createElement('style');
style.type = 'text/css';
style.appendChild(document.createTextNode(fontFace));
document.head.appendChild(style);

function replaceFontFamily(element) {
  if (element.nodeType === Node.ELEMENT_NODE) {
    const computedStyle = window.getComputedStyle(element);
    if (computedStyle.fontFamily.trim() === 'HUN') {
      element.style.fontFamily = `'HUN', 'BMHANNAAir'`;
    }
    if (computedStyle.fontFamily.trim() === 'PFW') {
      element.style.fontFamily = `'PFW', 'D2Coding'`;
    }
    if (computedStyle.fontFamily.trim() === 'C') {
      element.style.fontFamily = `'C', 'Pretendard JP'`;
    }
  }
}

function traverseAndReplaceFonts(node) {
  replaceFontFamily(node);
  node.childNodes.forEach(childNode => {
    traverseAndReplaceFonts(childNode);
  });
}

function isBlacklisted(node) {
  // 노드가 .chat_message.ig_chat_message.roomownerchat을 포함하고 있는지 확인
  // 노드가 .chat_message.system p를 포함하고 있지 않은 경우에만 블랙리스트 처리
  if (node.matches(".chat_message.ig_chat_message.roomownerchat")) {
    // 노드가 .chat_message.system p 자손을 포함하는 경우 블랙리스트 처리하지 않음
    if (node.querySelector(".chat_message.system p")) {
      return false;
    }
    return true;
  }
  return false;
}

function translateNode(node) {
  if (node.nodeType === Node.ELEMENT_NODE) {
    // 블랙리스트에 포함된 노드 건너뛰기
    if (isBlacklisted(node)) {
      return;
    }

    // .chat_message.ig_chat_message 요소 필터링 (다른 클래스가 없는 경우)
    if (node.matches(".chat_message.ig_chat_message") && node.classList.length === 2) {
      return;
    }
  }

  if (node.nodeType === Node.TEXT_NODE) {
    let text = node.textContent;
    let trimmedText = text.trim();
    // 원본 텍스트를 확인하여 앞뒤 공백을 유지
    if (TRANSLATIONS[text]) {
      node.textContent = TRANSLATIONS[text];
    } else if (TRANSLATIONS[trimmedText]) {
      node.textContent = text.replace(trimmedText, TRANSLATIONS[trimmedText]);
    }
  } else if (node.nodeType === Node.ELEMENT_NODE) {
    if (node.tagName === 'INPUT' && node.getAttribute('placeholder')) {
      let placeholderText = node.getAttribute('placeholder');
      let trimmedPlaceholder = placeholderText.trim();
      if (TRANSLATIONS[placeholderText]) {
        node.setAttribute('placeholder', TRANSLATIONS[placeholderText]);
      } else if (TRANSLATIONS[trimmedPlaceholder]) {
        node.setAttribute('placeholder', placeholderText.replace(trimmedPlaceholder, TRANSLATIONS[trimmedPlaceholder]));
      }
    }
    node.childNodes.forEach(childNode => {
      translateNode(childNode);
    });
  }
}

function translatePage() {
  document.querySelectorAll('body *').forEach(node => {
    translateNode(node);
  });
}

const observer = new MutationObserver(mutations => {
  mutations.forEach(mutation => {
    for (const [selector, regex, replace] of SELECTOR_TRANSLATIONS) {
      const targetElement = document.body.querySelector(selector);
      if (!targetElement) {
        continue;
      }

      const html = targetElement.innerHTML;
      if (regex.test(html)) {
        targetElement.innerHTML = html.replace(regex, replace);
      }
    }

    if (mutation.type === 'childList') {
      mutation.addedNodes.forEach(node => {
        translateNode(node);
        requestAnimationFrame(() => traverseAndReplaceFonts(node));  // 새로 추가된 노드에도 폰트 적용
      });
    }
  });
});

// body 요소에서 자손을 포함한 모든 변경 사항을 감시
observer.observe(document.body, {childList: true, subtree: true});

// 페이지 로드 시 폰트 교체 및 번역 실행
window.onload = function() {
  requestAnimationFrame(() => {
    document.querySelectorAll('body *').forEach(element => {
      replaceFontFamily(element);
    });
    translatePage();
  });
};
